server:
  port: 8081

spring:
  application:
    name: airplane-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    instance:
      hostname: localhost