server:
  port: 8083

flight:
  service: http://flight-service/
  path: flight/

spring:
  application:
    name: ticket-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    instance:
      hostname: localhost